// Exit control lock (ECL) models, options, trims and accessories — transcribed from 8-2026-DETEX-Price-List.pdf
// (Effective August 1, 2026), pages 85-94. GENERATED by tools/gen_ecl.py — do not hand-edit.
// Base prices are read from the spreadsheet at runtime (DETEX_DATA); pdfPrice is kept for audit only.
const ECL_RULES = {
 "models": {
  "ECL-230D": {
   "family": "D",
   "page": 85,
   "pdfPrice": 594,
   "label": "Exit Control Lock, UL-Listed Panic Hardware"
  },
  "ECL-230D-PH": {
   "family": "D",
   "page": 85,
   "pdfPrice": 680,
   "label": "Exit Control Lock w/ Long Bar, UL-Listed Panic Hardware"
  },
  "ECL-600": {
   "family": "F600",
   "page": 85,
   "pdfPrice": 1123,
   "label": "Fire Exit Hardware w/ Long Bar (Warnock Hersey, 3-hour)"
  },
  "ECL-230X": {
   "family": "SP",
   "page": 89,
   "pdfPrice": 1242,
   "label": "Single-Point Deadbolt Exit Control Lock"
  },
  "ECL-230X-W": {
   "family": "SP",
   "page": 89,
   "pdfPrice": 1585,
   "label": "Single-Point Deadbolt Exit Control Lock, Weatherized"
  },
  "ECL-230X-TD": {
   "family": "TD",
   "page": 90,
   "pdfPrice": 1940,
   "label": "2-Point Top Bolt and Deadbolt Exit Control Lock"
  },
  "ECL-230X-TB": {
   "family": "TB",
   "page": 90,
   "pdfPrice": 2095,
   "label": "2-Point Top and Bottom Bolt Exit Control Lock (cover lock standard)"
  },
  "ECL-230X-W-TD": {
   "family": "TD",
   "page": 90,
   "pdfPrice": 2283,
   "label": "2-Point Top Bolt and Deadbolt Exit Control Lock, Weatherized"
  },
  "ECL-230X-W-TB": {
   "family": "TB",
   "page": 90,
   "pdfPrice": 2438,
   "label": "2-Point Top and Bottom Bolt Exit Control Lock, Weatherized (cover lock standard)"
  },
  "ECL-230X-TDB": {
   "family": "TDB",
   "page": 91,
   "pdfPrice": 2330,
   "label": "3-Point Top Bolt, Deadbolt and Bottom Bolt Exit Control Lock"
  },
  "ECL-230X-W-TDB": {
   "family": "TDB",
   "page": 91,
   "pdfPrice": 2673,
   "label": "3-Point Top Bolt, Deadbolt and Bottom Bolt Exit Control Lock, Weatherized"
  }
 },
 "families": {
  "SP": {
   "H": {
    "price": 325,
    "label": "Hurricane Rated (includes the SN1 sex nut kits)",
    "page": 89
   },
   "DX1": {
    "price": 79,
    "label": "Adds one hinge-side locking point with mounting hardware",
    "page": 89,
    "black": 201
   },
   "DX2": {
    "price": 142,
    "label": "Adds two hinge-side locking points with mounting hardware",
    "page": 89,
    "black": 320
   },
   "DX3": {
    "price": 197,
    "label": "Adds three hinge-side locking points with mounting hardware",
    "page": 89,
    "black": 440
   },
   "30": {
    "price": 118,
    "label": "Fits 30\" wide door",
    "page": 89
   },
   "IP": {
    "price": 66,
    "label": "Inside Pull",
    "page": 89
   },
   "DDSK": {
    "price": 125,
    "label": "Double Door Strike Kit",
    "page": 89
   },
   "CL": {
    "price": 20,
    "label": "Cover Lock & 2 Keys (installed)",
    "page": 89
   },
   "SS": {
    "price": 35,
    "label": "Security Screws",
    "page": 89
   },
   "CL-SS": {
    "price": 55,
    "label": "Cover Lock & Security Screws",
    "page": 89
   },
   "RK": {
    "price": 59,
    "label": "ECL-230D Retrofit Kit (endcap plate and lock-body plate)",
    "page": 89
   },
   "SN1": {
    "price": 29,
    "label": "Sex Nut Kit (4 kits required)",
    "page": 89,
    "kits": 4,
    "perKit": true
   }
  },
  "TD": {
   "DX1": {
    "price": 79,
    "label": "Adds one hinge-side locking point with mounting hardware",
    "page": 90,
    "black": 201
   },
   "DX2": {
    "price": 142,
    "label": "Adds two hinge-side locking points with mounting hardware",
    "page": 90,
    "black": 320
   },
   "DX3": {
    "price": 197,
    "label": "Adds three hinge-side locking points with mounting hardware",
    "page": 90,
    "black": 440
   },
   "30": {
    "price": 118,
    "label": "Fits 30\" wide door",
    "page": 90
   },
   "84": {
    "price": 0,
    "label": "Fits 6'8\" to 7' door",
    "page": 90
   },
   "96": {
    "price": 118,
    "label": "Fits 7' to 8' door",
    "page": 90
   },
   "120": {
    "price": 118,
    "label": "Fits 8' to 10' door",
    "page": 90
   },
   "RC": {
    "price": 288,
    "label": "Rod Covers",
    "page": 90
   },
   "BG": {
    "price": 173,
    "label": "Bottom Bolt Guard",
    "page": 90
   },
   "RC-BG": {
    "price": 461,
    "label": "Rod Covers & Bottom Bolt Guard",
    "page": 90
   },
   "IP": {
    "price": 66,
    "label": "Inside Pull",
    "page": 90
   },
   "DDSK": {
    "price": 125,
    "label": "Double Door Strike Kit",
    "page": 90
   },
   "96B": {
    "price": 70,
    "label": "Dustproof Strike",
    "page": 90,
    "onlyModels": [
     "ECL-230X-TB",
     "ECL-230X-W-TB"
    ]
   },
   "96B-DDSK": {
    "price": 195,
    "label": "Dustproof Strike & Double Door Strike",
    "page": 90
   },
   "CL": {
    "price": 20,
    "label": "Cover Lock & 2 Keys (installed)",
    "page": 90
   },
   "SS": {
    "price": 35,
    "label": "Security Screws",
    "page": 90
   },
   "CL-SS": {
    "price": 55,
    "label": "Cover Lock & Security Screws",
    "page": 90
   },
   "RK": {
    "price": 59,
    "label": "ECL-230D Retrofit Kit (endcap plate and lock-body plate)",
    "page": 90
   },
   "SN1": {
    "price": 29,
    "label": "Sex Nut Kit (5 kits required)",
    "page": 90,
    "kits": 5,
    "perKit": true
   }
  },
  "TB": {
   "DX1": {
    "price": 79,
    "label": "Adds one hinge-side locking point with mounting hardware",
    "page": 90,
    "black": 201
   },
   "DX2": {
    "price": 142,
    "label": "Adds two hinge-side locking points with mounting hardware",
    "page": 90,
    "black": 320
   },
   "DX3": {
    "price": 197,
    "label": "Adds three hinge-side locking points with mounting hardware",
    "page": 90,
    "black": 440
   },
   "30": {
    "price": 118,
    "label": "Fits 30\" wide door",
    "page": 90
   },
   "84": {
    "price": 0,
    "label": "Fits 6'8\" to 7' door",
    "page": 90
   },
   "96": {
    "price": 118,
    "label": "Fits 7' to 8' door",
    "page": 90
   },
   "120": {
    "price": 118,
    "label": "Fits 8' to 10' door",
    "page": 90
   },
   "RC": {
    "price": 288,
    "label": "Rod Covers",
    "page": 90
   },
   "BG": {
    "price": 173,
    "label": "Bottom Bolt Guard",
    "page": 90
   },
   "RC-BG": {
    "price": 461,
    "label": "Rod Covers & Bottom Bolt Guard",
    "page": 90
   },
   "IP": {
    "price": 66,
    "label": "Inside Pull",
    "page": 90
   },
   "DDSK": {
    "price": 125,
    "label": "Double Door Strike Kit",
    "page": 90
   },
   "96B": {
    "price": 70,
    "label": "Dustproof Strike",
    "page": 90,
    "onlyModels": [
     "ECL-230X-TB",
     "ECL-230X-W-TB"
    ]
   },
   "96B-DDSK": {
    "price": 195,
    "label": "Dustproof Strike & Double Door Strike",
    "page": 90
   },
   "CL": {
    "price": 20,
    "label": "Cover Lock & 2 Keys (installed)",
    "page": 90,
    "standardNoCharge": true
   },
   "SS": {
    "price": 35,
    "label": "Security Screws",
    "page": 90
   },
   "CL-SS": {
    "price": 55,
    "label": "Cover Lock & Security Screws",
    "page": 90
   },
   "RK": {
    "price": 59,
    "label": "ECL-230D Retrofit Kit (endcap plate and lock-body plate)",
    "page": 90
   },
   "SN1": {
    "price": 29,
    "label": "Sex Nut Kit (6 kits required)",
    "page": 90,
    "kits": 6,
    "perKit": true
   }
  },
  "TDB": {
   "H": {
    "price": 325,
    "label": "Hurricane Rated (includes the SN1 sex nut kits)",
    "page": 91
   },
   "DX1": {
    "price": 79,
    "label": "Adds one hinge-side locking point with mounting hardware",
    "page": 91,
    "black": 201
   },
   "DX2": {
    "price": 142,
    "label": "Adds two hinge-side locking points with mounting hardware",
    "page": 91,
    "black": 320
   },
   "DX3": {
    "price": 197,
    "label": "Adds three hinge-side locking points with mounting hardware",
    "page": 91,
    "black": 440
   },
   "30": {
    "price": 118,
    "label": "Fits 30\" wide door",
    "page": 91
   },
   "84": {
    "price": 0,
    "label": "Fits 6'8\" to 7' door",
    "page": 91
   },
   "96": {
    "price": 118,
    "label": "Fits 7' to 8' door",
    "page": 91
   },
   "120": {
    "price": 118,
    "label": "Fits 8' to 10' door",
    "page": 91
   },
   "RC": {
    "price": 288,
    "label": "Rod Covers",
    "page": 91
   },
   "BG": {
    "price": 173,
    "label": "Bottom Bolt Guard",
    "page": 91
   },
   "RC-BG": {
    "price": 461,
    "label": "Rod Covers & Bottom Bolt Guard",
    "page": 91
   },
   "IP": {
    "price": 66,
    "label": "Inside Pull",
    "page": 91
   },
   "DDSK": {
    "price": 125,
    "label": "Double Door Strike Kit",
    "page": 91
   },
   "96B": {
    "price": 70,
    "label": "Dustproof Strike",
    "page": 91
   },
   "96B-DDSK": {
    "price": 195,
    "label": "Dustproof Strike & Double Door Strike",
    "page": 91
   },
   "CL": {
    "price": 20,
    "label": "Cover Lock & 2 Keys (installed)",
    "page": 91
   },
   "SS": {
    "price": 35,
    "label": "Security Screws",
    "page": 91
   },
   "CL-SS": {
    "price": 55,
    "label": "Cover Lock & Security Screws",
    "page": 91
   },
   "RK": {
    "price": 59,
    "label": "ECL-230D Retrofit Kit (endcap plate and lock-body plate)",
    "page": 91
   },
   "SN1": {
    "price": 29,
    "label": "Sex Nut Kit (6 kits required)",
    "page": 91,
    "kits": 6,
    "perKit": true
   }
  }
 },
 "sn1Kits": {
  "SP": 4,
  "TD": 5,
  "TB": 6,
  "TDB": 6
 },
 "xTrims": {
  "03T": {
   "price": 269,
   "label": "Trim Plate with Outside Key Control (OKC)",
   "page": 92
  },
  "01T": {
   "price": 269,
   "label": "Trim Plate without OKC",
   "page": 92
  },
  "03PP": {
   "price": 269,
   "label": "Pull Plate with OKC",
   "page": 92
  },
  "01PP": {
   "price": 269,
   "label": "Pull Plate without OKC",
   "page": 92
  }
 },
 "accessories": {
  "PP-5572": {
   "price": 19,
   "label": "Replacement Cover Lock & 2 Keys",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-KIT": {
   "price": 29,
   "label": "Set of all Cover Lock Keys (key numbers 11 through 20)",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-11": {
   "price": 8,
   "label": "Cover Lock Key, key number 11",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-12": {
   "price": 8,
   "label": "Cover Lock Key, key number 12",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-13": {
   "price": 8,
   "label": "Cover Lock Key, key number 13",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-14": {
   "price": 8,
   "label": "Cover Lock Key, key number 14",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-15": {
   "price": 8,
   "label": "Cover Lock Key, key number 15",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-16": {
   "price": 8,
   "label": "Cover Lock Key, key number 16",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-17": {
   "price": 8,
   "label": "Cover Lock Key, key number 17",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-18": {
   "price": 8,
   "label": "Cover Lock Key, key number 18",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-19": {
   "price": 8,
   "label": "Cover Lock Key, key number 19",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-405-20": {
   "price": 8,
   "label": "Cover Lock Key, key number 20",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-2105K": {
   "price": 127,
   "label": "Field Conversion Kit, 36\"-48\" door width, metal photoluminescent plate",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-436K": {
   "price": 41,
   "label": "Bar Guard Kit (for standard ECL-230D)",
   "page": 86,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-2100K": {
   "price": 104,
   "label": "Bar Guard Kit (for ECL-230D-PH & ECL-600)",
   "page": 86,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-475K": {
   "price": 105,
   "label": "Decorative Back Plate Kit",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-498K": {
   "price": 245,
   "label": "Outside Pull and Warning Sign",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH"
   ],
   "note": "Not for use on fire rated doors."
  },
  "ECL-2111K": {
   "price": 152,
   "label": "6V-to-9V Conversion Kit (ECL-230D and ECL-230C only)",
   "page": 86,
   "models": [
    "ECL-230D"
   ]
  },
  "DDH-2250": {
   "price": 230,
   "label": "Double Door Holder (ECL-230 Series and V40 Series)",
   "page": 86,
   "models": [
    "ECL-230D",
    "ECL-230D-PH",
    "ECL-230X",
    "ECL-230X-W",
    "ECL-230X-TD",
    "ECL-230X-TB",
    "ECL-230X-W-TD",
    "ECL-230X-W-TB",
    "ECL-230X-TDB",
    "ECL-230X-W-TDB"
   ]
  },
  "ECL-8220": {
   "price": 32,
   "label": "Metal Exit Bar Plate, English (Red) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-8220-1": {
   "price": 32,
   "label": "Metal Exit Bar Plate, English (Green) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-8220-6": {
   "price": 32,
   "label": "Metal Exit Bar Plate, Chinese (Red) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-8220-7": {
   "price": 32,
   "label": "Metal Exit Bar Plate, French Canadian (Red) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-8220-8": {
   "price": 32,
   "label": "Metal Exit Bar Plate, Spanish (Red) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-8220-9": {
   "price": 32,
   "label": "Metal Exit Bar Plate, Chinese (Green) (for ECL-230D)",
   "page": 87,
   "models": [
    "ECL-230D"
   ]
  },
  "ECL-2109": {
   "price": 43,
   "label": "Metal Exit Bar Plate, English (Red) (for ECL-230D-PH and ECL-600)",
   "page": 87,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-2109-1": {
   "price": 95,
   "label": "Metal Exit Bar Plate, English (Green) (for ECL-230D-PH and ECL-600)",
   "page": 87,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "106687-1": {
   "price": 95,
   "label": "Metal Exit Bar Plate, French Canadian (Red) (for ECL-230D-PH and ECL-600)",
   "page": 87,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "106687-2": {
   "price": 95,
   "label": "Metal Exit Bar Plate, Chinese (Red) (for ECL-230D-PH and ECL-600)",
   "page": 87,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "106687-3": {
   "price": 95,
   "label": "Metal Exit Bar Plate, Chinese (Green) (for ECL-230D-PH and ECL-600)",
   "page": 87,
   "models": [
    "ECL-230D-PH",
    "ECL-600"
   ]
  },
  "ECL-439K": {
   "price": 85,
   "label": "Mortise Strike Plate Kit",
   "page": 87,
   "models": [
    "ECL-230D",
    "ECL-230D-PH"
   ]
  },
  "ECL-435K": {
   "price": 35,
   "label": "Adjustable Surface Keeper, \"L\" & \"Z\" bracket for double door applications",
   "page": 87,
   "models": [
    "ECL-230D",
    "ECL-230D-PH"
   ]
  },
  "ECL-437K": {
   "price": 85,
   "label": "Adjustable Surface Keeper (standard)",
   "page": 87,
   "models": [
    "ECL-230D",
    "ECL-230D-PH"
   ]
  },
  "ECL-620": {
   "price": 504,
   "label": "Outside Lever Trim for ECL-600 (lever retracts latch bolt only, rim cylinder operates deadbolt; black only, field reversible)",
   "page": 85,
   "models": [
    "ECL-600"
   ]
  }
 },
 "vra": {
  "B": {
   "84": 791,
   "96": 959,
   "120": 1043
  },
  "C": {
   "84": 834,
   "96": 1027
  },
  "D": {
   "84": 2033,
   "96": 1892
  }
 },
 "cylinder": {
  "price": 126,
  "page": 94,
  "codes": {
   "RC65": "Rim Cylinder, Schlage \"C\" keyway",
   "C65": "Rim Cylinder, Schlage \"C\" keyway",
   "IC7R": "SFIC Interchangeable Core Rim Cylinder Housing (core not included)"
  }
 }
};
