// Per-function electrified options & accessories — transcribed from 8-2026-DETEX-Price-List.pdf
// (Effective August 1, 2026): Advantex pp.35-41, Value Series pp.56-61, controllers pp.66-68.
// GENERATED by gen_electrified.py — do not hand-edit; regenerate from the PDF.
const ELECTRIFIED_OPTIONS = {
 "ADVANTEX": {
  "EA": {
   "page": 35,
   "base": 627,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 35
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 35
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 35
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 35
    },
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 35
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 35
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 35
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 35
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 35
    }
   },
   "accessories": {
    "PP-5152-2": {
     "label": "Transformer 24VAC",
     "price": 127,
     "page": 35,
     "controller": false
    },
    "PP-5152-3": {
     "label": "Transformer 12VAC",
     "price": 59,
     "page": 35,
     "controller": false
    }
   }
  },
  "EB W": {
   "page": 35,
   "base": 743,
   "options": {
    "FC3EC1W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 460,
     "page": 35
    },
    "FC10EC1W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 560,
     "page": 35
    },
    "FC3EC2W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 260,
     "page": 35
    },
    "FC10EC2W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 360,
     "page": 35
    },
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 35
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 35
    }
   },
   "accessories": {
    "106595-5": {
     "label": "Battery Eliminator 9VDC Power Source in NEMA Enclosure",
     "price": 2225,
     "page": 35,
     "controller": false
    }
   }
  },
  "ER EX": {
   "page": 36,
   "base": 1542,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 36
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 36
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 36
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 36
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 36
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 36
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 36
    }
   },
   "accessories": {
    "81-800": {
     "label": "Power Supply Controller for Latch Retraction - Single Door",
     "price": 1540,
     "page": 66,
     "controller": true
    },
    "82-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Simultaneous",
     "price": 1740,
     "page": 66,
     "controller": true
    },
    "83-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Independent",
     "price": 2138,
     "page": 66,
     "controller": true
    }
   }
  },
  "ER EX W": {
   "page": 36,
   "base": 2427,
   "options": {
    "FC3EC1W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 460,
     "page": 36
    },
    "FC10EC1W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 560,
     "page": 36
    },
    "FC3EC2W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 260,
     "page": 36
    },
    "FC10EC2W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 360,
     "page": 36
    }
   },
   "accessories": {
    "81-800": {
     "label": "Power Supply Controller for Latch Retraction - Single Door",
     "price": 1540,
     "page": 66,
     "controller": true
    },
    "82-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Simultaneous",
     "price": 1740,
     "page": 66,
     "controller": true
    },
    "83-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Independent",
     "price": 2138,
     "page": 66,
     "controller": true
    }
   }
  },
  "EI": {
   "page": 37,
   "base": 463,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 37
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 37
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 37
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 37
    },
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 37
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 37
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 37
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 37
    }
   },
   "accessories": {
    "10-800": {
     "label": "Logic Controller for Electric Integration",
     "price": 2240,
     "page": 68,
     "controller": true
    },
    "11-800": {
     "label": "Logic Controller for Electric Integration",
     "price": 2539,
     "page": 68,
     "controller": true
    }
   }
  },
  "ED": {
   "page": 37,
   "base": 808,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 37
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 37
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 37
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 37
    },
    "EX": {
     "label": "Request to Exit Switching",
     "price": 284,
     "page": 37
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 37
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 37
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 37
    }
   },
   "accessories": {
    "CS462": {
     "label": "Keyswitch",
     "price": 280,
     "page": 37,
     "controller": false
    },
    "PP-5152-2": {
     "label": "24VAC Transformer",
     "price": 127,
     "page": 37,
     "controller": false
    }
   }
  },
  "EE": {
   "page": 38,
   "base": 2703,
   "options": {
    "1": {
     "label": "1 Second Arming",
     "price": 0,
     "page": 38
    },
    "30": {
     "label": "30-Second Delayed Egress",
     "price": 0,
     "page": 38
    },
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 38
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 38
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 38
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 38
    },
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 38
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 38
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 38
    },
    "SA": {
     "label": "Silent Arming",
     "price": 242,
     "page": 38
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 38
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 38
    },
    "L9": {
     "label": "Less Battery",
     "price": 11,
     "page": 38
    },
    "SI": {
     "label": "Status Indicator",
     "price": 9,
     "page": 38
    },
    "PS0": {
     "label": "Less Power Supply",
     "price": -225,
     "page": 38
    }
   },
   "accessories": {}
  },
  "EEX": {
   "page": 38,
   "base": 1797,
   "options": {},
   "accessories": {
    "12-800": {
     "label": "Logic Controller",
     "price": 2656,
     "page": 68,
     "controller": true
    }
   }
  },
  "EEX W": {
   "page": 38,
   "base": 1797,
   "options": {},
   "accessories": {
    "106595-1": {
     "label": "Logic Controller in NEMA enclosure for use outdoors",
     "price": 4864,
     "page": 68,
     "controller": true
    }
   }
  },
  "EE ER EX": {
   "page": 39,
   "base": 3806,
   "options": {
    "30": {
     "label": "30-Second Delayed Egress",
     "price": 0,
     "page": 39
    },
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 39
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 39
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 39
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 39
    },
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 39
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 39
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 39
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 39
    }
   },
   "accessories": {
    "84-800": {
     "label": "Power Supply Controller for single doors (includes wall-mount key switch & Horn interface box)",
     "price": 3286,
     "page": 67,
     "controller": true
    },
    "85-800": {
     "label": "Power Supply Controller for pairs of doors (includes wall-mount key switch & Horn interface box)",
     "price": 4182,
     "page": 67,
     "controller": true
    }
   }
  },
  "ES": {
   "page": 39,
   "base": 395,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 39
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 39
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 39
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 39
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 39
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 39
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 39
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 39
    }
   },
   "accessories": {}
  },
  "EX": {
   "page": 40,
   "base": 284,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 40
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 40
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 40
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 40
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 40
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 40
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 40
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 40
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 40
    }
   },
   "accessories": {}
  },
  "EX W": {
   "page": 40,
   "base": 162,
   "options": {
    "FC3EC1W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 460,
     "page": 40
    },
    "FC10EC1W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 560,
     "page": 40
    },
    "FC3EC2W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 260,
     "page": 40
    },
    "FC10EC2W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 360,
     "page": 40
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 40
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 40
    }
   },
   "accessories": {}
  },
  "LX": {
   "page": 40,
   "base": 314,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 40
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 40
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 40
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 40
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 40
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 40
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 40
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 40
    }
   },
   "accessories": {
    "MS-1039S": {
     "label": "Magnetic Switch (Surface)",
     "price": 96,
     "page": 40,
     "controller": false
    },
    "MS-1059S": {
     "label": "Magnetic Switch (Surface)",
     "price": 96,
     "page": 40,
     "controller": false
    },
    "MS-1039F": {
     "label": "Magnetic Switch (Flush)",
     "price": 55,
     "page": 40,
     "controller": false
    },
    "MS-1059F": {
     "label": "Magnetic Switch (Flush)",
     "price": 55,
     "page": 40,
     "controller": false
    }
   }
  },
  "LXV": {
   "page": 41,
   "base": 493,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 41
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 41
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 41
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 41
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 41
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 41
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 41
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 41
    }
   },
   "accessories": {
    "MS-1039S": {
     "label": "Magnetic Switch (Surface)",
     "price": 96,
     "page": 41,
     "controller": false
    },
    "MS-1059S": {
     "label": "Magnetic Switch (Surface)",
     "price": 96,
     "page": 41,
     "controller": false
    },
    "MS-1039F": {
     "label": "Magnetic Switch (Flush)",
     "price": 55,
     "page": 41,
     "controller": false
    },
    "MS-1059F": {
     "label": "Magnetic Switch (Flush)",
     "price": 55,
     "page": 41,
     "controller": false
    }
   }
  },
  "EXV": {
   "page": 41,
   "base": 430,
   "options": {
    "FC3EC1": {
     "label": "Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 380,
     "page": 41
    },
    "FC10EC1": {
     "label": "Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 440,
     "page": 41
    },
    "FC3EC2": {
     "label": "Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 120,
     "page": 41
    },
    "FC10EC2": {
     "label": "Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 200,
     "page": 41
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 41
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 41
    },
    "LX": {
     "label": "Latch Bolt Signaling Switch",
     "price": 314,
     "page": 41
    },
    "2": {
     "label": "Includes 2 High-Current Switches (EXV2)",
     "price": 428,
     "page": 41
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 41
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 41
    }
   },
   "accessories": {}
  },
  "EXV W": {
   "page": 41,
   "base": 357,
   "options": {
    "FC3EC1W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, ramped endcap and fittings",
     "price": 460,
     "page": 41,
     "pdfPrintedPrice": 275
    },
    "FC10EC1W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, ramped endcap and fittings",
     "price": 560,
     "page": 41,
     "pdfPrintedPrice": 294
    },
    "FC3EC2W": {
     "label": "Weatherized Flex Conduit Kit (3’) includes conduit, flush endcap and fittings",
     "price": 260,
     "page": 41,
     "pdfPrintedPrice": 148
    },
    "FC10EC2W": {
     "label": "Weatherized Flex Conduit Kit (10’) includes conduit, flush endcap and fittings",
     "price": 360,
     "page": 41,
     "pdfPrintedPrice": 213
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 41
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 41
    }
   },
   "accessories": {}
  }
 },
 "VALUE SERIES": {
  "EA": {
   "page": 56,
   "base": 563,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 56
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 56
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 56
    },
    "BLK": {
     "label": "Black pushpad (includes peel & stick door signage “Emergency Exit Only Alarm Will Sound”)",
     "price": 0,
     "page": 56
    },
    "IN": {
     "label": "220V to 24VAC Transformer substituted for standard transformer",
     "price": 0,
     "page": 56
    },
    "277": {
     "label": "277V to 24VAC Transformer substituted for standard transformer",
     "price": 53,
     "page": 56
    },
    "LBM": {
     "label": "Latch Bolt Monitoring - V40 only (alarm triggered by dead latch)",
     "price": 55,
     "page": 56
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 56
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 56
    }
   },
   "accessories": {}
  },
  "EB": {
   "page": 56,
   "base": 270,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 56
    },
    "FC3": {
     "label": "3’ Flexible Conduit and fittings",
     "price": 64,
     "page": 56
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 56
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 56
    },
    "BLK": {
     "label": "Black pushpad (includes peel & stick door signage “Emergency Exit Only Alarm Will Sound”)",
     "price": 0,
     "page": 56
    },
    "LBM": {
     "label": "Latch Bolt Monitoring - V40 only (alarm triggered by dead latch)",
     "price": 55,
     "page": 56
    }
   },
   "accessories": {
    "BE-961-1": {
     "label": "Battery Eliminator 9VDC Power Source",
     "price": 407,
     "page": 56,
     "controller": false
    }
   }
  },
  "EB W": {
   "page": 57,
   "base": 529,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 57
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 57
    },
    "BLK": {
     "label": "Black pushpad (includes peel & stick door signage “Emergency Exit Only Alarm Will Sound”)",
     "price": 0,
     "page": 57
    },
    "FC3W": {
     "label": "Weatherized 3’ Flexible Conduit and fittings",
     "price": 103,
     "page": 57
    },
    "FC10W": {
     "label": "Weatherized 10’ Flexible Conduit and fittings",
     "price": 236,
     "page": 57
    }
   },
   "accessories": {
    "106595-5": {
     "label": "Battery Eliminator 9VDC Power Source in NEMA Enclosure",
     "price": 2225,
     "page": 57,
     "controller": false
    }
   }
  },
  "ED": {
   "page": 57,
   "base": 768,
   "options": {
    "IN": {
     "label": "220V to 24VAC Transformer",
     "price": 0,
     "page": 57
    },
    "EX": {
     "label": "Request to Exit Switching",
     "price": 212,
     "page": 57
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 57
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 57
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 57
    }
   },
   "accessories": {
    "CS462": {
     "label": "Keyswitch",
     "price": 280,
     "page": 57,
     "controller": false
    },
    "PP-5152-2": {
     "label": "24VAC Transformer",
     "price": 127,
     "page": 57,
     "controller": false
    }
   }
  },
  "ER EX": {
   "page": 58,
   "base": 1653,
   "options": {
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 58
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 58
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 58
    }
   },
   "accessories": {
    "81-800": {
     "label": "Power Supply Controller for Latch Retraction - Single Door",
     "price": 1540,
     "page": 66,
     "controller": true
    },
    "82-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Simultaneous",
     "price": 1740,
     "page": 66,
     "controller": true
    },
    "83-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Independent",
     "price": 2138,
     "page": 66,
     "controller": true
    }
   }
  },
  "ER EX W": {
   "page": 58,
   "base": 2390,
   "options": {
    "FC10W": {
     "label": "Weatherized 10’ Flexible Conduit and fittings",
     "price": 236,
     "page": 58
    }
   },
   "accessories": {
    "81-800": {
     "label": "Power Supply Controller for Latch Retraction - Single Door",
     "price": 1540,
     "page": 66,
     "controller": true
    },
    "82-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Simultaneous",
     "price": 1740,
     "page": 66,
     "controller": true
    },
    "83-800": {
     "label": "Power Supply Controller for Latch Retraction - Pairs of Doors Independent",
     "price": 2138,
     "page": 66,
     "controller": true
    }
   }
  },
  "ES": {
   "page": 58,
   "base": 251,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 58
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 58
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 58
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 58
    },
    "RWE": {
     "label": "Red pushpad with white signage (English) - other languages available",
     "price": 0,
     "page": 58
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 58
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 58
    }
   },
   "accessories": {}
  },
  "EE": {
   "page": 59,
   "base": 2455,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 59
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 59
    },
    "30": {
     "label": "30-Second Delayed Egress",
     "price": 0,
     "page": 59
    },
    "BLK": {
     "label": "Black pushpad (includes peel & stick door signage “Emergency Exit Only Alarm Will Sound”)",
     "price": 0,
     "page": 59
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 59
    },
    "SA": {
     "label": "Silent Arming",
     "price": 242,
     "page": 59
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 59
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 59
    },
    "L9": {
     "label": "Less Battery",
     "price": 11,
     "page": 59
    },
    "SI": {
     "label": "Status Indicator",
     "price": 9,
     "page": 59
    },
    "PS0": {
     "label": "Less Power Supply",
     "price": -225,
     "page": 59
    }
   },
   "accessories": {}
  },
  "EEX": {
   "page": 59,
   "base": 1299,
   "options": {},
   "accessories": {
    "12-800": {
     "label": "Logic Controller",
     "price": 2656,
     "page": 68,
     "controller": true
    }
   }
  },
  "EEX W": {
   "page": 59,
   "base": 1342,
   "options": {},
   "accessories": {
    "106595-1": {
     "label": "Logic Controller in NEMA enclosure for use outdoors",
     "price": 4864,
     "page": 68,
     "controller": true
    }
   }
  },
  "EI": {
   "page": 60,
   "base": 295,
   "options": {
    "KS": {
     "label": "Keystop feature installed",
     "price": 11,
     "page": 60
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 60
    },
    "RWE": {
     "label": "Red pushpad with white signage (English) - other languages available",
     "price": 0,
     "page": 60
    },
    "FC3": {
     "label": "3’ Flexible Conduit and fittings",
     "price": 64,
     "page": 60
    },
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 60
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 60
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 60
    }
   },
   "accessories": {
    "10-800": {
     "label": "Logic Controller & Power Supply for Electric Integration",
     "price": 2240,
     "page": 68,
     "controller": true
    },
    "11-800": {
     "label": "Logic Controller & Power Supply for Electric Integration",
     "price": 2539,
     "page": 68,
     "controller": true
    }
   }
  },
  "EX": {
   "page": 60,
   "base": 227,
   "options": {
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 60
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 60
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 60
    },
    "RWE": {
     "label": "Red pushpad with white signage (English) - other languages available",
     "price": 0,
     "page": 60
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 60
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 60
    }
   },
   "accessories": {}
  },
  "EX W": {
   "page": 60,
   "base": 88,
   "options": {
    "FC10W": {
     "label": "Weatherized 10’ Flexible Conduit and fittings",
     "price": 236,
     "page": 60
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 60
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 60
    }
   },
   "accessories": {}
  },
  "EXV": {
   "page": 61,
   "base": 356,
   "options": {
    "FC10": {
     "label": "10’ Flexible Conduit and fittings",
     "price": 117,
     "page": 61
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 61
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 61
    },
    "2": {
     "label": "Includes 2 High Current Switches (EXV2)",
     "price": 327,
     "page": 61
    },
    "PT-5": {
     "label": "Power Transfer",
     "price": 230,
     "page": 61
    },
    "EWH8-626": {
     "label": "Electric Hinge",
     "price": 551,
     "page": 61
    }
   },
   "accessories": {}
  },
  "EXV W": {
   "page": 61,
   "base": 193,
   "options": {
    "FC10W": {
     "label": "Weatherized 10’ Flexible Conduit and fittings",
     "price": 236,
     "page": 61,
     "pdfPrintedPrice": 123
    },
    "CD": {
     "label": "Cylinder Dogging",
     "price": 0,
     "page": 61
    },
    "LD": {
     "label": "Less Dogging",
     "price": 0,
     "page": 61
    },
    "2": {
     "label": "Includes 2 High Current Switches (EXV2)",
     "price": 327,
     "page": 61
    }
   },
   "accessories": {}
  }
 }
};
